service: flask-hello-world

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-east-2
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: hello.APP
    packRequirements:
      dockerizePip: false
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
