version: 2.1

jobs:
  test:
    docker:
      - image: python:3.7.2-alpine
    steps:
      - checkout
      - pip install -r requirements.txt
      - run: python -m unittest discover -s tests

workflows:
   version: 2.1
   alm-deploy:
     jobs:
       - test


