version: 2.1

jobs:
  test:
    docker:
      - image: python:3.7.2-alpine
    steps:
      - checkout
      - run: python -m unittest discover -s tests

workflows:
   version: 2.1
   jobs:
     - test


