version: 2.1

jobs:
  serverless-deploy:
    docker:
      - image: node:10.15.3-alpine
    steps:
        - checkout
        - run: npm install serverless -g
        - run: npm install
        - run: sls deploy --alias dev
  test:
    docker:
      - image: python:2.7-alpine3.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -s tests

workflows:
   version: 2.1
   alm-deploy:
     jobs:
       - test
       - serverless-deploy


