version: 2.1

jobs:
  test:
    docker:
      - image: python:2.7-alpine3.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -s tests
  serverless-deploy:
    docker:
      - image: node:10.15.3-alpine
    steps:
      - checkout
      - run: ls
      - run: npm install serverless
      - run: npm install
      - run: apk add python py-pip
      - run: ./node_modules/.bin/sls deploy --alias $alias


workflows:
   version: 2.1
   build-deploy:
     jobs:
       - test
       - serverless-deploy:
           name: deploy-dev
           requires:
              - test
           context: dev
           filters:
             branches:
               only: master
       - hold:
           type: approval
       - serverless-deploy:
           name: deploy-test
           requires:
             - deploy-dev
             - hold
           context: test
           filters:
             branches:
               only: master





